### ISSUE TITLE
A language spec !

### ISSUE THREAD

**Issue by crlf0710** [ErichDonGubler/not-yet-awesome-rust#28]
An (even incomplete and informal) language specification document can help people understand the concepts and details of the language. It will aid the documentation of libstd in many ways.

**Comment by ErichDonGubler** [comment]
Just to make it clear, I'm assuming you're talking about the Rust language (since it wasn't explicit, but seems pretty obvious).

An initial search yields:

* A (unofficial?) stub for an [English specification](https://github.com/rust-specification/english-specification) of Rust.
* Rust has its own documentation for a formal [grammar](https://doc.rust-lang.org/grammar.html).

**Comment by ErichDonGubler** [comment]
What exactly are the use cases? I know that there's several, and I'm more than happy to do some research myself, but I want to hear it from you. I've already heard one, though I think it could use some more concrete detail:

> It will aid the documentation of libstd in many ways.

How will it help document `libstd`? What users does this serve, and why is it important to them?

**Comment by crlf0710** [comment]
> An initial search yields:

There's also a reference too: https://doc.rust-lang.org/stable/reference/

**Comment by crlf0710** [comment]
> How will it help document `libstd`?

Sorry for my bad english, i meant it will *complement* the current `libstd` documentation, and give a more general and central "once and for all" introduction of the concepts and ideas for all those language items. The process of developing it will also clean up the technical vocabulary (and slang) and help resolving the ambiguities in description around Rust the language, It may also clarify many if not all the corner cases, and help the development of a test suite. i believe it is important but not urgent.

**Comment by ErichDonGubler** [comment]
So far as I can tell, the Rust reference is incomplete at this point because the *language* is unstable. This seems largely out of the control of library authors, and something that would definitely be a priority for the Rust community (which I imagine would have a call for participation) years from now, when there's more stability with Rust in general.

I guess what I'm saying is I'm not sure if this item really has a place on this list because I don't see that it's very actionable -- does that make sense? If we can break this down into tasks of some sort, I might be happy to discuss this, but as things stand, I'm planning on closing this this coming Tuesday if no further discussion happens here.

**Comment by ErichDonGubler** [comment]
No more discussion has been had, so...closing this.
